// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jty/snapcard/ent/card"
	"github.com/jty/snapcard/ent/deck"
	"github.com/jty/snapcard/ent/reviewlog"
	"github.com/jty/snapcard/ent/user"
)

// CardCreate is the builder for creating a Card entity.
type CardCreate struct {
	config
	mutation *CardMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *CardCreate) SetUserID(v int) *CardCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDeckID sets the "deck_id" field.
func (_c *CardCreate) SetDeckID(v int) *CardCreate {
	_c.mutation.SetDeckID(v)
	return _c
}

// SetFront sets the "front" field.
func (_c *CardCreate) SetFront(v string) *CardCreate {
	_c.mutation.SetFront(v)
	return _c
}

// SetBack sets the "back" field.
func (_c *CardCreate) SetBack(v string) *CardCreate {
	_c.mutation.SetBack(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *CardCreate) SetTags(v []string) *CardCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetSourceImageURL sets the "source_image_url" field.
func (_c *CardCreate) SetSourceImageURL(v string) *CardCreate {
	_c.mutation.SetSourceImageURL(v)
	return _c
}

// SetNillableSourceImageURL sets the "source_image_url" field if the given value is not nil.
func (_c *CardCreate) SetNillableSourceImageURL(v *string) *CardCreate {
	if v != nil {
		_c.SetSourceImageURL(*v)
	}
	return _c
}

// SetStability sets the "stability" field.
func (_c *CardCreate) SetStability(v float64) *CardCreate {
	_c.mutation.SetStability(v)
	return _c
}

// SetNillableStability sets the "stability" field if the given value is not nil.
func (_c *CardCreate) SetNillableStability(v *float64) *CardCreate {
	if v != nil {
		_c.SetStability(*v)
	}
	return _c
}

// SetDifficulty sets the "difficulty" field.
func (_c *CardCreate) SetDifficulty(v float64) *CardCreate {
	_c.mutation.SetDifficulty(v)
	return _c
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_c *CardCreate) SetNillableDifficulty(v *float64) *CardCreate {
	if v != nil {
		_c.SetDifficulty(*v)
	}
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *CardCreate) SetDueDate(v time.Time) *CardCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_c *CardCreate) SetNillableDueDate(v *time.Time) *CardCreate {
	if v != nil {
		_c.SetDueDate(*v)
	}
	return _c
}

// SetReps sets the "reps" field.
func (_c *CardCreate) SetReps(v int) *CardCreate {
	_c.mutation.SetReps(v)
	return _c
}

// SetNillableReps sets the "reps" field if the given value is not nil.
func (_c *CardCreate) SetNillableReps(v *int) *CardCreate {
	if v != nil {
		_c.SetReps(*v)
	}
	return _c
}

// SetLapses sets the "lapses" field.
func (_c *CardCreate) SetLapses(v int) *CardCreate {
	_c.mutation.SetLapses(v)
	return _c
}

// SetNillableLapses sets the "lapses" field if the given value is not nil.
func (_c *CardCreate) SetNillableLapses(v *int) *CardCreate {
	if v != nil {
		_c.SetLapses(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *CardCreate) SetState(v card.State) *CardCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *CardCreate) SetNillableState(v *card.State) *CardCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CardCreate) SetCreatedAt(v time.Time) *CardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CardCreate) SetNillableCreatedAt(v *time.Time) *CardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CardCreate) SetUpdatedAt(v time.Time) *CardCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CardCreate) SetNillableUpdatedAt(v *time.Time) *CardCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CardCreate) SetUser(v *User) *CardCreate {
	return _c.SetUserID(v.ID)
}

// SetDeck sets the "deck" edge to the Deck entity.
func (_c *CardCreate) SetDeck(v *Deck) *CardCreate {
	return _c.SetDeckID(v.ID)
}

// AddReviewLogIDs adds the "review_logs" edge to the ReviewLog entity by IDs.
func (_c *CardCreate) AddReviewLogIDs(ids ...int) *CardCreate {
	_c.mutation.AddReviewLogIDs(ids...)
	return _c
}

// AddReviewLogs adds the "review_logs" edges to the ReviewLog entity.
func (_c *CardCreate) AddReviewLogs(v ...*ReviewLog) *CardCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewLogIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (_c *CardCreate) Mutation() *CardMutation {
	return _c.mutation
}

// Save creates the Card in the database.
func (_c *CardCreate) Save(ctx context.Context) (*Card, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CardCreate) SaveX(ctx context.Context) *Card {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CardCreate) defaults() {
	if _, ok := _c.mutation.Stability(); !ok {
		v := card.DefaultStability
		_c.mutation.SetStability(v)
	}
	if _, ok := _c.mutation.Difficulty(); !ok {
		v := card.DefaultDifficulty
		_c.mutation.SetDifficulty(v)
	}
	if _, ok := _c.mutation.DueDate(); !ok {
		v := card.DefaultDueDate()
		_c.mutation.SetDueDate(v)
	}
	if _, ok := _c.mutation.Reps(); !ok {
		v := card.DefaultReps
		_c.mutation.SetReps(v)
	}
	if _, ok := _c.mutation.Lapses(); !ok {
		v := card.DefaultLapses
		_c.mutation.SetLapses(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := card.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := card.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := card.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CardCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Card.user_id"`)}
	}
	if _, ok := _c.mutation.DeckID(); !ok {
		return &ValidationError{Name: "deck_id", err: errors.New(`ent: missing required field "Card.deck_id"`)}
	}
	if _, ok := _c.mutation.Front(); !ok {
		return &ValidationError{Name: "front", err: errors.New(`ent: missing required field "Card.front"`)}
	}
	if v, ok := _c.mutation.Front(); ok {
		if err := card.FrontValidator(v); err != nil {
			return &ValidationError{Name: "front", err: fmt.Errorf(`ent: validator failed for field "Card.front": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Back(); !ok {
		return &ValidationError{Name: "back", err: errors.New(`ent: missing required field "Card.back"`)}
	}
	if v, ok := _c.mutation.Back(); ok {
		if err := card.BackValidator(v); err != nil {
			return &ValidationError{Name: "back", err: fmt.Errorf(`ent: validator failed for field "Card.back": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stability(); !ok {
		return &ValidationError{Name: "stability", err: errors.New(`ent: missing required field "Card.stability"`)}
	}
	if _, ok := _c.mutation.Difficulty(); !ok {
		return &ValidationError{Name: "difficulty", err: errors.New(`ent: missing required field "Card.difficulty"`)}
	}
	if _, ok := _c.mutation.DueDate(); !ok {
		return &ValidationError{Name: "due_date", err: errors.New(`ent: missing required field "Card.due_date"`)}
	}
	if _, ok := _c.mutation.Reps(); !ok {
		return &ValidationError{Name: "reps", err: errors.New(`ent: missing required field "Card.reps"`)}
	}
	if _, ok := _c.mutation.Lapses(); !ok {
		return &ValidationError{Name: "lapses", err: errors.New(`ent: missing required field "Card.lapses"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Card.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := card.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Card.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Card.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Card.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Card.user"`)}
	}
	if len(_c.mutation.DeckIDs()) == 0 {
		return &ValidationError{Name: "deck", err: errors.New(`ent: missing required edge "Card.deck"`)}
	}
	return nil
}

func (_c *CardCreate) sqlSave(ctx context.Context) (*Card, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CardCreate) createSpec() (*Card, *sqlgraph.CreateSpec) {
	var (
		_node = &Card{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(card.Table, sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Front(); ok {
		_spec.SetField(card.FieldFront, field.TypeString, value)
		_node.Front = value
	}
	if value, ok := _c.mutation.Back(); ok {
		_spec.SetField(card.FieldBack, field.TypeString, value)
		_node.Back = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(card.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.SourceImageURL(); ok {
		_spec.SetField(card.FieldSourceImageURL, field.TypeString, value)
		_node.SourceImageURL = &value
	}
	if value, ok := _c.mutation.Stability(); ok {
		_spec.SetField(card.FieldStability, field.TypeFloat64, value)
		_node.Stability = value
	}
	if value, ok := _c.mutation.Difficulty(); ok {
		_spec.SetField(card.FieldDifficulty, field.TypeFloat64, value)
		_node.Difficulty = value
	}
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(card.FieldDueDate, field.TypeTime, value)
		_node.DueDate = value
	}
	if value, ok := _c.mutation.Reps(); ok {
		_spec.SetField(card.FieldReps, field.TypeInt, value)
		_node.Reps = value
	}
	if value, ok := _c.mutation.Lapses(); ok {
		_spec.SetField(card.FieldLapses, field.TypeInt, value)
		_node.Lapses = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(card.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(card.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(card.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.UserTable,
			Columns: []string{card.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeckIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.DeckTable,
			Columns: []string{card.DeckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeckID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.ReviewLogsTable,
			Columns: []string{card.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CardCreateBulk is the builder for creating many Card entities in bulk.
type CardCreateBulk struct {
	config
	err      error
	builders []*CardCreate
}

// Save creates the Card entities in the database.
func (_c *CardCreateBulk) Save(ctx context.Context) ([]*Card, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Card, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CardCreateBulk) SaveX(ctx context.Context) []*Card {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
