// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/jty/snapcard/ent/card"
	"github.com/jty/snapcard/ent/deck"
	"github.com/jty/snapcard/ent/user"
)

// Card is the model entity for the Card schema.
type Card struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// DeckID holds the value of the "deck_id" field.
	DeckID int `json:"deck_id,omitempty"`
	// Front holds the value of the "front" field.
	Front string `json:"front,omitempty"`
	// Back holds the value of the "back" field.
	Back string `json:"back,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// SourceImageURL holds the value of the "source_image_url" field.
	SourceImageURL *string `json:"source_image_url,omitempty"`
	// Stability holds the value of the "stability" field.
	Stability float64 `json:"stability,omitempty"`
	// Difficulty holds the value of the "difficulty" field.
	Difficulty float64 `json:"difficulty,omitempty"`
	// DueDate holds the value of the "due_date" field.
	DueDate time.Time `json:"due_date,omitempty"`
	// Reps holds the value of the "reps" field.
	Reps int `json:"reps,omitempty"`
	// Lapses holds the value of the "lapses" field.
	Lapses int `json:"lapses,omitempty"`
	// State holds the value of the "state" field.
	State card.State `json:"state,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CardQuery when eager-loading is set.
	Edges        CardEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CardEdges holds the relations/edges for other nodes in the graph.
type CardEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Deck holds the value of the deck edge.
	Deck *Deck `json:"deck,omitempty"`
	// ReviewLogs holds the value of the review_logs edge.
	ReviewLogs []*ReviewLog `json:"review_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// DeckOrErr returns the Deck value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardEdges) DeckOrErr() (*Deck, error) {
	if e.Deck != nil {
		return e.Deck, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: deck.Label}
	}
	return nil, &NotLoadedError{edge: "deck"}
}

// ReviewLogsOrErr returns the ReviewLogs value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) ReviewLogsOrErr() ([]*ReviewLog, error) {
	if e.loadedTypes[2] {
		return e.ReviewLogs, nil
	}
	return nil, &NotLoadedError{edge: "review_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Card) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case card.FieldTags:
			values[i] = new([]byte)
		case card.FieldStability, card.FieldDifficulty:
			values[i] = new(sql.NullFloat64)
		case card.FieldID, card.FieldUserID, card.FieldDeckID, card.FieldReps, card.FieldLapses:
			values[i] = new(sql.NullInt64)
		case card.FieldFront, card.FieldBack, card.FieldSourceImageURL, card.FieldState:
			values[i] = new(sql.NullString)
		case card.FieldDueDate, card.FieldCreatedAt, card.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Card fields.
func (_m *Card) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case card.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case card.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case card.FieldDeckID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deck_id", values[i])
			} else if value.Valid {
				_m.DeckID = int(value.Int64)
			}
		case card.FieldFront:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field front", values[i])
			} else if value.Valid {
				_m.Front = value.String
			}
		case card.FieldBack:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field back", values[i])
			} else if value.Valid {
				_m.Back = value.String
			}
		case card.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case card.FieldSourceImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_image_url", values[i])
			} else if value.Valid {
				_m.SourceImageURL = new(string)
				*_m.SourceImageURL = value.String
			}
		case card.FieldStability:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field stability", values[i])
			} else if value.Valid {
				_m.Stability = value.Float64
			}
		case card.FieldDifficulty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field difficulty", values[i])
			} else if value.Valid {
				_m.Difficulty = value.Float64
			}
		case card.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				_m.DueDate = value.Time
			}
		case card.FieldReps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reps", values[i])
			} else if value.Valid {
				_m.Reps = int(value.Int64)
			}
		case card.FieldLapses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lapses", values[i])
			} else if value.Valid {
				_m.Lapses = int(value.Int64)
			}
		case card.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = card.State(value.String)
			}
		case card.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case card.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Card.
// This includes values selected through modifiers, order, etc.
func (_m *Card) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Card entity.
func (_m *Card) QueryUser() *UserQuery {
	return NewCardClient(_m.config).QueryUser(_m)
}

// QueryDeck queries the "deck" edge of the Card entity.
func (_m *Card) QueryDeck() *DeckQuery {
	return NewCardClient(_m.config).QueryDeck(_m)
}

// QueryReviewLogs queries the "review_logs" edge of the Card entity.
func (_m *Card) QueryReviewLogs() *ReviewLogQuery {
	return NewCardClient(_m.config).QueryReviewLogs(_m)
}

// Update returns a builder for updating this Card.
// Note that you need to call Card.Unwrap() before calling this method if this Card
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Card) Update() *CardUpdateOne {
	return NewCardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Card entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Card) Unwrap() *Card {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Card is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Card) String() string {
	var builder strings.Builder
	builder.WriteString("Card(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("deck_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeckID))
	builder.WriteString(", ")
	builder.WriteString("front=")
	builder.WriteString(_m.Front)
	builder.WriteString(", ")
	builder.WriteString("back=")
	builder.WriteString(_m.Back)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	if v := _m.SourceImageURL; v != nil {
		builder.WriteString("source_image_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("stability=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stability))
	builder.WriteString(", ")
	builder.WriteString("difficulty=")
	builder.WriteString(fmt.Sprintf("%v", _m.Difficulty))
	builder.WriteString(", ")
	builder.WriteString("due_date=")
	builder.WriteString(_m.DueDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reps=")
	builder.WriteString(fmt.Sprintf("%v", _m.Reps))
	builder.WriteString(", ")
	builder.WriteString("lapses=")
	builder.WriteString(fmt.Sprintf("%v", _m.Lapses))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Cards is a parsable slice of Card.
type Cards []*Card
