// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/jty/snapcard/ent/card"
	"github.com/jty/snapcard/ent/deck"
	"github.com/jty/snapcard/ent/predicate"
	"github.com/jty/snapcard/ent/reviewlog"
	"github.com/jty/snapcard/ent/user"
)

// CardUpdate is the builder for updating Card entities.
type CardUpdate struct {
	config
	hooks    []Hook
	mutation *CardMutation
}

// Where appends a list predicates to the CardUpdate builder.
func (_u *CardUpdate) Where(ps ...predicate.Card) *CardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CardUpdate) SetUserID(v int) *CardUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillableUserID(v *int) *CardUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeckID sets the "deck_id" field.
func (_u *CardUpdate) SetDeckID(v int) *CardUpdate {
	_u.mutation.SetDeckID(v)
	return _u
}

// SetNillableDeckID sets the "deck_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillableDeckID(v *int) *CardUpdate {
	if v != nil {
		_u.SetDeckID(*v)
	}
	return _u
}

// SetFront sets the "front" field.
func (_u *CardUpdate) SetFront(v string) *CardUpdate {
	_u.mutation.SetFront(v)
	return _u
}

// SetNillableFront sets the "front" field if the given value is not nil.
func (_u *CardUpdate) SetNillableFront(v *string) *CardUpdate {
	if v != nil {
		_u.SetFront(*v)
	}
	return _u
}

// SetBack sets the "back" field.
func (_u *CardUpdate) SetBack(v string) *CardUpdate {
	_u.mutation.SetBack(v)
	return _u
}

// SetNillableBack sets the "back" field if the given value is not nil.
func (_u *CardUpdate) SetNillableBack(v *string) *CardUpdate {
	if v != nil {
		_u.SetBack(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *CardUpdate) SetTags(v []string) *CardUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *CardUpdate) AppendTags(v []string) *CardUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *CardUpdate) ClearTags() *CardUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetSourceImageURL sets the "source_image_url" field.
func (_u *CardUpdate) SetSourceImageURL(v string) *CardUpdate {
	_u.mutation.SetSourceImageURL(v)
	return _u
}

// SetNillableSourceImageURL sets the "source_image_url" field if the given value is not nil.
func (_u *CardUpdate) SetNillableSourceImageURL(v *string) *CardUpdate {
	if v != nil {
		_u.SetSourceImageURL(*v)
	}
	return _u
}

// ClearSourceImageURL clears the value of the "source_image_url" field.
func (_u *CardUpdate) ClearSourceImageURL() *CardUpdate {
	_u.mutation.ClearSourceImageURL()
	return _u
}

// SetStability sets the "stability" field.
func (_u *CardUpdate) SetStability(v float64) *CardUpdate {
	_u.mutation.ResetStability()
	_u.mutation.SetStability(v)
	return _u
}

// SetNillableStability sets the "stability" field if the given value is not nil.
func (_u *CardUpdate) SetNillableStability(v *float64) *CardUpdate {
	if v != nil {
		_u.SetStability(*v)
	}
	return _u
}

// AddStability adds value to the "stability" field.
func (_u *CardUpdate) AddStability(v float64) *CardUpdate {
	_u.mutation.AddStability(v)
	return _u
}

// SetDifficulty sets the "difficulty" field.
func (_u *CardUpdate) SetDifficulty(v float64) *CardUpdate {
	_u.mutation.ResetDifficulty()
	_u.mutation.SetDifficulty(v)
	return _u
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_u *CardUpdate) SetNillableDifficulty(v *float64) *CardUpdate {
	if v != nil {
		_u.SetDifficulty(*v)
	}
	return _u
}

// AddDifficulty adds value to the "difficulty" field.
func (_u *CardUpdate) AddDifficulty(v float64) *CardUpdate {
	_u.mutation.AddDifficulty(v)
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *CardUpdate) SetDueDate(v time.Time) *CardUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *CardUpdate) SetNillableDueDate(v *time.Time) *CardUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// SetReps sets the "reps" field.
func (_u *CardUpdate) SetReps(v int) *CardUpdate {
	_u.mutation.ResetReps()
	_u.mutation.SetReps(v)
	return _u
}

// SetNillableReps sets the "reps" field if the given value is not nil.
func (_u *CardUpdate) SetNillableReps(v *int) *CardUpdate {
	if v != nil {
		_u.SetReps(*v)
	}
	return _u
}

// AddReps adds value to the "reps" field.
func (_u *CardUpdate) AddReps(v int) *CardUpdate {
	_u.mutation.AddReps(v)
	return _u
}

// SetLapses sets the "lapses" field.
func (_u *CardUpdate) SetLapses(v int) *CardUpdate {
	_u.mutation.ResetLapses()
	_u.mutation.SetLapses(v)
	return _u
}

// SetNillableLapses sets the "lapses" field if the given value is not nil.
func (_u *CardUpdate) SetNillableLapses(v *int) *CardUpdate {
	if v != nil {
		_u.SetLapses(*v)
	}
	return _u
}

// AddLapses adds value to the "lapses" field.
func (_u *CardUpdate) AddLapses(v int) *CardUpdate {
	_u.mutation.AddLapses(v)
	return _u
}

// SetState sets the "state" field.
func (_u *CardUpdate) SetState(v card.State) *CardUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CardUpdate) SetNillableState(v *card.State) *CardUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CardUpdate) SetCreatedAt(v time.Time) *CardUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CardUpdate) SetNillableCreatedAt(v *time.Time) *CardUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CardUpdate) SetUpdatedAt(v time.Time) *CardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CardUpdate) SetUser(v *User) *CardUpdate {
	return _u.SetUserID(v.ID)
}

// SetDeck sets the "deck" edge to the Deck entity.
func (_u *CardUpdate) SetDeck(v *Deck) *CardUpdate {
	return _u.SetDeckID(v.ID)
}

// AddReviewLogIDs adds the "review_logs" edge to the ReviewLog entity by IDs.
func (_u *CardUpdate) AddReviewLogIDs(ids ...int) *CardUpdate {
	_u.mutation.AddReviewLogIDs(ids...)
	return _u
}

// AddReviewLogs adds the "review_logs" edges to the ReviewLog entity.
func (_u *CardUpdate) AddReviewLogs(v ...*ReviewLog) *CardUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewLogIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (_u *CardUpdate) Mutation() *CardMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CardUpdate) ClearUser() *CardUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearDeck clears the "deck" edge to the Deck entity.
func (_u *CardUpdate) ClearDeck() *CardUpdate {
	_u.mutation.ClearDeck()
	return _u
}

// ClearReviewLogs clears all "review_logs" edges to the ReviewLog entity.
func (_u *CardUpdate) ClearReviewLogs() *CardUpdate {
	_u.mutation.ClearReviewLogs()
	return _u
}

// RemoveReviewLogIDs removes the "review_logs" edge to ReviewLog entities by IDs.
func (_u *CardUpdate) RemoveReviewLogIDs(ids ...int) *CardUpdate {
	_u.mutation.RemoveReviewLogIDs(ids...)
	return _u
}

// RemoveReviewLogs removes "review_logs" edges to ReviewLog entities.
func (_u *CardUpdate) RemoveReviewLogs(v ...*ReviewLog) *CardUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := card.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUpdate) check() error {
	if v, ok := _u.mutation.Front(); ok {
		if err := card.FrontValidator(v); err != nil {
			return &ValidationError{Name: "front", err: fmt.Errorf(`ent: validator failed for field "Card.front": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Back(); ok {
		if err := card.BackValidator(v); err != nil {
			return &ValidationError{Name: "back", err: fmt.Errorf(`ent: validator failed for field "Card.back": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := card.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Card.state": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Card.user"`)
	}
	if _u.mutation.DeckCleared() && len(_u.mutation.DeckIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Card.deck"`)
	}
	return nil
}

func (_u *CardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Front(); ok {
		_spec.SetField(card.FieldFront, field.TypeString, value)
	}
	if value, ok := _u.mutation.Back(); ok {
		_spec.SetField(card.FieldBack, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(card.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, card.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(card.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.SourceImageURL(); ok {
		_spec.SetField(card.FieldSourceImageURL, field.TypeString, value)
	}
	if _u.mutation.SourceImageURLCleared() {
		_spec.ClearField(card.FieldSourceImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Stability(); ok {
		_spec.SetField(card.FieldStability, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStability(); ok {
		_spec.AddField(card.FieldStability, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Difficulty(); ok {
		_spec.SetField(card.FieldDifficulty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDifficulty(); ok {
		_spec.AddField(card.FieldDifficulty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(card.FieldDueDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Reps(); ok {
		_spec.SetField(card.FieldReps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReps(); ok {
		_spec.AddField(card.FieldReps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Lapses(); ok {
		_spec.SetField(card.FieldLapses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLapses(); ok {
		_spec.AddField(card.FieldLapses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(card.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(card.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(card.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.UserTable,
			Columns: []string{card.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.UserTable,
			Columns: []string{card.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeckCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.DeckTable,
			Columns: []string{card.DeckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeckIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.DeckTable,
			Columns: []string{card.DeckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.ReviewLogsTable,
			Columns: []string{card.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewLogsIDs(); len(nodes) > 0 && !_u.mutation.ReviewLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.ReviewLogsTable,
			Columns: []string{card.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.ReviewLogsTable,
			Columns: []string{card.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CardUpdateOne is the builder for updating a single Card entity.
type CardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CardMutation
}

// SetUserID sets the "user_id" field.
func (_u *CardUpdateOne) SetUserID(v int) *CardUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableUserID(v *int) *CardUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeckID sets the "deck_id" field.
func (_u *CardUpdateOne) SetDeckID(v int) *CardUpdateOne {
	_u.mutation.SetDeckID(v)
	return _u
}

// SetNillableDeckID sets the "deck_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableDeckID(v *int) *CardUpdateOne {
	if v != nil {
		_u.SetDeckID(*v)
	}
	return _u
}

// SetFront sets the "front" field.
func (_u *CardUpdateOne) SetFront(v string) *CardUpdateOne {
	_u.mutation.SetFront(v)
	return _u
}

// SetNillableFront sets the "front" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableFront(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetFront(*v)
	}
	return _u
}

// SetBack sets the "back" field.
func (_u *CardUpdateOne) SetBack(v string) *CardUpdateOne {
	_u.mutation.SetBack(v)
	return _u
}

// SetNillableBack sets the "back" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableBack(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetBack(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *CardUpdateOne) SetTags(v []string) *CardUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *CardUpdateOne) AppendTags(v []string) *CardUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *CardUpdateOne) ClearTags() *CardUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetSourceImageURL sets the "source_image_url" field.
func (_u *CardUpdateOne) SetSourceImageURL(v string) *CardUpdateOne {
	_u.mutation.SetSourceImageURL(v)
	return _u
}

// SetNillableSourceImageURL sets the "source_image_url" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableSourceImageURL(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetSourceImageURL(*v)
	}
	return _u
}

// ClearSourceImageURL clears the value of the "source_image_url" field.
func (_u *CardUpdateOne) ClearSourceImageURL() *CardUpdateOne {
	_u.mutation.ClearSourceImageURL()
	return _u
}

// SetStability sets the "stability" field.
func (_u *CardUpdateOne) SetStability(v float64) *CardUpdateOne {
	_u.mutation.ResetStability()
	_u.mutation.SetStability(v)
	return _u
}

// SetNillableStability sets the "stability" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableStability(v *float64) *CardUpdateOne {
	if v != nil {
		_u.SetStability(*v)
	}
	return _u
}

// AddStability adds value to the "stability" field.
func (_u *CardUpdateOne) AddStability(v float64) *CardUpdateOne {
	_u.mutation.AddStability(v)
	return _u
}

// SetDifficulty sets the "difficulty" field.
func (_u *CardUpdateOne) SetDifficulty(v float64) *CardUpdateOne {
	_u.mutation.ResetDifficulty()
	_u.mutation.SetDifficulty(v)
	return _u
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableDifficulty(v *float64) *CardUpdateOne {
	if v != nil {
		_u.SetDifficulty(*v)
	}
	return _u
}

// AddDifficulty adds value to the "difficulty" field.
func (_u *CardUpdateOne) AddDifficulty(v float64) *CardUpdateOne {
	_u.mutation.AddDifficulty(v)
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *CardUpdateOne) SetDueDate(v time.Time) *CardUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableDueDate(v *time.Time) *CardUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// SetReps sets the "reps" field.
func (_u *CardUpdateOne) SetReps(v int) *CardUpdateOne {
	_u.mutation.ResetReps()
	_u.mutation.SetReps(v)
	return _u
}

// SetNillableReps sets the "reps" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableReps(v *int) *CardUpdateOne {
	if v != nil {
		_u.SetReps(*v)
	}
	return _u
}

// AddReps adds value to the "reps" field.
func (_u *CardUpdateOne) AddReps(v int) *CardUpdateOne {
	_u.mutation.AddReps(v)
	return _u
}

// SetLapses sets the "lapses" field.
func (_u *CardUpdateOne) SetLapses(v int) *CardUpdateOne {
	_u.mutation.ResetLapses()
	_u.mutation.SetLapses(v)
	return _u
}

// SetNillableLapses sets the "lapses" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableLapses(v *int) *CardUpdateOne {
	if v != nil {
		_u.SetLapses(*v)
	}
	return _u
}

// AddLapses adds value to the "lapses" field.
func (_u *CardUpdateOne) AddLapses(v int) *CardUpdateOne {
	_u.mutation.AddLapses(v)
	return _u
}

// SetState sets the "state" field.
func (_u *CardUpdateOne) SetState(v card.State) *CardUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableState(v *card.State) *CardUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CardUpdateOne) SetCreatedAt(v time.Time) *CardUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableCreatedAt(v *time.Time) *CardUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CardUpdateOne) SetUpdatedAt(v time.Time) *CardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CardUpdateOne) SetUser(v *User) *CardUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetDeck sets the "deck" edge to the Deck entity.
func (_u *CardUpdateOne) SetDeck(v *Deck) *CardUpdateOne {
	return _u.SetDeckID(v.ID)
}

// AddReviewLogIDs adds the "review_logs" edge to the ReviewLog entity by IDs.
func (_u *CardUpdateOne) AddReviewLogIDs(ids ...int) *CardUpdateOne {
	_u.mutation.AddReviewLogIDs(ids...)
	return _u
}

// AddReviewLogs adds the "review_logs" edges to the ReviewLog entity.
func (_u *CardUpdateOne) AddReviewLogs(v ...*ReviewLog) *CardUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewLogIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (_u *CardUpdateOne) Mutation() *CardMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CardUpdateOne) ClearUser() *CardUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearDeck clears the "deck" edge to the Deck entity.
func (_u *CardUpdateOne) ClearDeck() *CardUpdateOne {
	_u.mutation.ClearDeck()
	return _u
}

// ClearReviewLogs clears all "review_logs" edges to the ReviewLog entity.
func (_u *CardUpdateOne) ClearReviewLogs() *CardUpdateOne {
	_u.mutation.ClearReviewLogs()
	return _u
}

// RemoveReviewLogIDs removes the "review_logs" edge to ReviewLog entities by IDs.
func (_u *CardUpdateOne) RemoveReviewLogIDs(ids ...int) *CardUpdateOne {
	_u.mutation.RemoveReviewLogIDs(ids...)
	return _u
}

// RemoveReviewLogs removes "review_logs" edges to ReviewLog entities.
func (_u *CardUpdateOne) RemoveReviewLogs(v ...*ReviewLog) *CardUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewLogIDs(ids...)
}

// Where appends a list predicates to the CardUpdate builder.
func (_u *CardUpdateOne) Where(ps ...predicate.Card) *CardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CardUpdateOne) Select(field string, fields ...string) *CardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Card entity.
func (_u *CardUpdateOne) Save(ctx context.Context) (*Card, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUpdateOne) SaveX(ctx context.Context) *Card {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := card.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUpdateOne) check() error {
	if v, ok := _u.mutation.Front(); ok {
		if err := card.FrontValidator(v); err != nil {
			return &ValidationError{Name: "front", err: fmt.Errorf(`ent: validator failed for field "Card.front": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Back(); ok {
		if err := card.BackValidator(v); err != nil {
			return &ValidationError{Name: "back", err: fmt.Errorf(`ent: validator failed for field "Card.back": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := card.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Card.state": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Card.user"`)
	}
	if _u.mutation.DeckCleared() && len(_u.mutation.DeckIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Card.deck"`)
	}
	return nil
}

func (_u *CardUpdateOne) sqlSave(ctx context.Context) (_node *Card, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Card.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, card.FieldID)
		for _, f := range fields {
			if !card.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != card.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Front(); ok {
		_spec.SetField(card.FieldFront, field.TypeString, value)
	}
	if value, ok := _u.mutation.Back(); ok {
		_spec.SetField(card.FieldBack, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(card.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, card.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(card.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.SourceImageURL(); ok {
		_spec.SetField(card.FieldSourceImageURL, field.TypeString, value)
	}
	if _u.mutation.SourceImageURLCleared() {
		_spec.ClearField(card.FieldSourceImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Stability(); ok {
		_spec.SetField(card.FieldStability, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStability(); ok {
		_spec.AddField(card.FieldStability, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Difficulty(); ok {
		_spec.SetField(card.FieldDifficulty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDifficulty(); ok {
		_spec.AddField(card.FieldDifficulty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(card.FieldDueDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Reps(); ok {
		_spec.SetField(card.FieldReps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReps(); ok {
		_spec.AddField(card.FieldReps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Lapses(); ok {
		_spec.SetField(card.FieldLapses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLapses(); ok {
		_spec.AddField(card.FieldLapses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(card.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(card.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(card.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.UserTable,
			Columns: []string{card.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.UserTable,
			Columns: []string{card.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeckCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.DeckTable,
			Columns: []string{card.DeckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeckIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.DeckTable,
			Columns: []string{card.DeckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.ReviewLogsTable,
			Columns: []string{card.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewLogsIDs(); len(nodes) > 0 && !_u.mutation.ReviewLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.ReviewLogsTable,
			Columns: []string{card.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.ReviewLogsTable,
			Columns: []string{card.ReviewLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Card{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
