// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jty/snapcard/ent/predicate"
	"github.com/jty/snapcard/ent/reviewlog"
)

// ReviewLogDelete is the builder for deleting a ReviewLog entity.
type ReviewLogDelete struct {
	config
	hooks    []Hook
	mutation *ReviewLogMutation
}

// Where appends a list predicates to the ReviewLogDelete builder.
func (_d *ReviewLogDelete) Where(ps ...predicate.ReviewLog) *ReviewLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ReviewLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReviewLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ReviewLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(reviewlog.Table, sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ReviewLogDeleteOne is the builder for deleting a single ReviewLog entity.
type ReviewLogDeleteOne struct {
	_d *ReviewLogDelete
}

// Where appends a list predicates to the ReviewLogDelete builder.
func (_d *ReviewLogDeleteOne) Where(ps ...predicate.ReviewLog) *ReviewLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ReviewLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reviewlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReviewLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
