// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jty/snapcard/ent/card"
	"github.com/jty/snapcard/ent/predicate"
	"github.com/jty/snapcard/ent/reviewlog"
	"github.com/jty/snapcard/ent/user"
)

// ReviewLogUpdate is the builder for updating ReviewLog entities.
type ReviewLogUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewLogMutation
}

// Where appends a list predicates to the ReviewLogUpdate builder.
func (_u *ReviewLogUpdate) Where(ps ...predicate.ReviewLog) *ReviewLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ReviewLogUpdate) SetUserID(v int) *ReviewLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableUserID(v *int) *ReviewLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCardID sets the "card_id" field.
func (_u *ReviewLogUpdate) SetCardID(v int) *ReviewLogUpdate {
	_u.mutation.SetCardID(v)
	return _u
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableCardID(v *int) *ReviewLogUpdate {
	if v != nil {
		_u.SetCardID(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *ReviewLogUpdate) SetRating(v int) *ReviewLogUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableRating(v *int) *ReviewLogUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewLogUpdate) AddRating(v int) *ReviewLogUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetReviewMode sets the "review_mode" field.
func (_u *ReviewLogUpdate) SetReviewMode(v reviewlog.ReviewMode) *ReviewLogUpdate {
	_u.mutation.SetReviewMode(v)
	return _u
}

// SetNillableReviewMode sets the "review_mode" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableReviewMode(v *reviewlog.ReviewMode) *ReviewLogUpdate {
	if v != nil {
		_u.SetReviewMode(*v)
	}
	return _u
}

// SetUserAnswer sets the "user_answer" field.
func (_u *ReviewLogUpdate) SetUserAnswer(v string) *ReviewLogUpdate {
	_u.mutation.SetUserAnswer(v)
	return _u
}

// SetNillableUserAnswer sets the "user_answer" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableUserAnswer(v *string) *ReviewLogUpdate {
	if v != nil {
		_u.SetUserAnswer(*v)
	}
	return _u
}

// ClearUserAnswer clears the value of the "user_answer" field.
func (_u *ReviewLogUpdate) ClearUserAnswer() *ReviewLogUpdate {
	_u.mutation.ClearUserAnswer()
	return _u
}

// SetAiCorrect sets the "ai_correct" field.
func (_u *ReviewLogUpdate) SetAiCorrect(v bool) *ReviewLogUpdate {
	_u.mutation.SetAiCorrect(v)
	return _u
}

// SetNillableAiCorrect sets the "ai_correct" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableAiCorrect(v *bool) *ReviewLogUpdate {
	if v != nil {
		_u.SetAiCorrect(*v)
	}
	return _u
}

// ClearAiCorrect clears the value of the "ai_correct" field.
func (_u *ReviewLogUpdate) ClearAiCorrect() *ReviewLogUpdate {
	_u.mutation.ClearAiCorrect()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ReviewLogUpdate) SetReviewedAt(v time.Time) *ReviewLogUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ReviewLogUpdate) SetNillableReviewedAt(v *time.Time) *ReviewLogUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ReviewLogUpdate) SetUser(v *User) *ReviewLogUpdate {
	return _u.SetUserID(v.ID)
}

// SetCard sets the "card" edge to the Card entity.
func (_u *ReviewLogUpdate) SetCard(v *Card) *ReviewLogUpdate {
	return _u.SetCardID(v.ID)
}

// Mutation returns the ReviewLogMutation object of the builder.
func (_u *ReviewLogUpdate) Mutation() *ReviewLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ReviewLogUpdate) ClearUser() *ReviewLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearCard clears the "card" edge to the Card entity.
func (_u *ReviewLogUpdate) ClearCard() *ReviewLogUpdate {
	_u.mutation.ClearCard()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReviewLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReviewLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewLogUpdate) check() error {
	if v, ok := _u.mutation.Rating(); ok {
		if err := reviewlog.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "ReviewLog.rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewMode(); ok {
		if err := reviewlog.ReviewModeValidator(v); err != nil {
			return &ValidationError{Name: "review_mode", err: fmt.Errorf(`ent: validator failed for field "ReviewLog.review_mode": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReviewLog.user"`)
	}
	if _u.mutation.CardCleared() && len(_u.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReviewLog.card"`)
	}
	return nil
}

func (_u *ReviewLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reviewlog.Table, reviewlog.Columns, sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(reviewlog.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(reviewlog.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewMode(); ok {
		_spec.SetField(reviewlog.FieldReviewMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UserAnswer(); ok {
		_spec.SetField(reviewlog.FieldUserAnswer, field.TypeString, value)
	}
	if _u.mutation.UserAnswerCleared() {
		_spec.ClearField(reviewlog.FieldUserAnswer, field.TypeString)
	}
	if value, ok := _u.mutation.AiCorrect(); ok {
		_spec.SetField(reviewlog.FieldAiCorrect, field.TypeBool, value)
	}
	if _u.mutation.AiCorrectCleared() {
		_spec.ClearField(reviewlog.FieldAiCorrect, field.TypeBool)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(reviewlog.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.UserTable,
			Columns: []string{reviewlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.UserTable,
			Columns: []string{reviewlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.CardTable,
			Columns: []string{reviewlog.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.CardTable,
			Columns: []string{reviewlog.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reviewlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReviewLogUpdateOne is the builder for updating a single ReviewLog entity.
type ReviewLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewLogMutation
}

// SetUserID sets the "user_id" field.
func (_u *ReviewLogUpdateOne) SetUserID(v int) *ReviewLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableUserID(v *int) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCardID sets the "card_id" field.
func (_u *ReviewLogUpdateOne) SetCardID(v int) *ReviewLogUpdateOne {
	_u.mutation.SetCardID(v)
	return _u
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableCardID(v *int) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetCardID(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *ReviewLogUpdateOne) SetRating(v int) *ReviewLogUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableRating(v *int) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewLogUpdateOne) AddRating(v int) *ReviewLogUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetReviewMode sets the "review_mode" field.
func (_u *ReviewLogUpdateOne) SetReviewMode(v reviewlog.ReviewMode) *ReviewLogUpdateOne {
	_u.mutation.SetReviewMode(v)
	return _u
}

// SetNillableReviewMode sets the "review_mode" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableReviewMode(v *reviewlog.ReviewMode) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetReviewMode(*v)
	}
	return _u
}

// SetUserAnswer sets the "user_answer" field.
func (_u *ReviewLogUpdateOne) SetUserAnswer(v string) *ReviewLogUpdateOne {
	_u.mutation.SetUserAnswer(v)
	return _u
}

// SetNillableUserAnswer sets the "user_answer" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableUserAnswer(v *string) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetUserAnswer(*v)
	}
	return _u
}

// ClearUserAnswer clears the value of the "user_answer" field.
func (_u *ReviewLogUpdateOne) ClearUserAnswer() *ReviewLogUpdateOne {
	_u.mutation.ClearUserAnswer()
	return _u
}

// SetAiCorrect sets the "ai_correct" field.
func (_u *ReviewLogUpdateOne) SetAiCorrect(v bool) *ReviewLogUpdateOne {
	_u.mutation.SetAiCorrect(v)
	return _u
}

// SetNillableAiCorrect sets the "ai_correct" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableAiCorrect(v *bool) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetAiCorrect(*v)
	}
	return _u
}

// ClearAiCorrect clears the value of the "ai_correct" field.
func (_u *ReviewLogUpdateOne) ClearAiCorrect() *ReviewLogUpdateOne {
	_u.mutation.ClearAiCorrect()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ReviewLogUpdateOne) SetReviewedAt(v time.Time) *ReviewLogUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ReviewLogUpdateOne) SetNillableReviewedAt(v *time.Time) *ReviewLogUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ReviewLogUpdateOne) SetUser(v *User) *ReviewLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetCard sets the "card" edge to the Card entity.
func (_u *ReviewLogUpdateOne) SetCard(v *Card) *ReviewLogUpdateOne {
	return _u.SetCardID(v.ID)
}

// Mutation returns the ReviewLogMutation object of the builder.
func (_u *ReviewLogUpdateOne) Mutation() *ReviewLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ReviewLogUpdateOne) ClearUser() *ReviewLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearCard clears the "card" edge to the Card entity.
func (_u *ReviewLogUpdateOne) ClearCard() *ReviewLogUpdateOne {
	_u.mutation.ClearCard()
	return _u
}

// Where appends a list predicates to the ReviewLogUpdate builder.
func (_u *ReviewLogUpdateOne) Where(ps ...predicate.ReviewLog) *ReviewLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReviewLogUpdateOne) Select(field string, fields ...string) *ReviewLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReviewLog entity.
func (_u *ReviewLogUpdateOne) Save(ctx context.Context) (*ReviewLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewLogUpdateOne) SaveX(ctx context.Context) *ReviewLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReviewLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewLogUpdateOne) check() error {
	if v, ok := _u.mutation.Rating(); ok {
		if err := reviewlog.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "ReviewLog.rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewMode(); ok {
		if err := reviewlog.ReviewModeValidator(v); err != nil {
			return &ValidationError{Name: "review_mode", err: fmt.Errorf(`ent: validator failed for field "ReviewLog.review_mode": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReviewLog.user"`)
	}
	if _u.mutation.CardCleared() && len(_u.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReviewLog.card"`)
	}
	return nil
}

func (_u *ReviewLogUpdateOne) sqlSave(ctx context.Context) (_node *ReviewLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reviewlog.Table, reviewlog.Columns, sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReviewLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reviewlog.FieldID)
		for _, f := range fields {
			if !reviewlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reviewlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(reviewlog.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(reviewlog.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewMode(); ok {
		_spec.SetField(reviewlog.FieldReviewMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UserAnswer(); ok {
		_spec.SetField(reviewlog.FieldUserAnswer, field.TypeString, value)
	}
	if _u.mutation.UserAnswerCleared() {
		_spec.ClearField(reviewlog.FieldUserAnswer, field.TypeString)
	}
	if value, ok := _u.mutation.AiCorrect(); ok {
		_spec.SetField(reviewlog.FieldAiCorrect, field.TypeBool, value)
	}
	if _u.mutation.AiCorrectCleared() {
		_spec.ClearField(reviewlog.FieldAiCorrect, field.TypeBool)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(reviewlog.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.UserTable,
			Columns: []string{reviewlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.UserTable,
			Columns: []string{reviewlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.CardTable,
			Columns: []string{reviewlog.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.CardTable,
			Columns: []string{reviewlog.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReviewLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reviewlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
