// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jty/snapcard/ent/card"
	"github.com/jty/snapcard/ent/predicate"
	"github.com/jty/snapcard/ent/reviewlog"
	"github.com/jty/snapcard/ent/user"
)

// ReviewLogQuery is the builder for querying ReviewLog entities.
type ReviewLogQuery struct {
	config
	ctx        *QueryContext
	order      []reviewlog.OrderOption
	inters     []Interceptor
	predicates []predicate.ReviewLog
	withUser   *UserQuery
	withCard   *CardQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReviewLogQuery builder.
func (_q *ReviewLogQuery) Where(ps ...predicate.ReviewLog) *ReviewLogQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ReviewLogQuery) Limit(limit int) *ReviewLogQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ReviewLogQuery) Offset(offset int) *ReviewLogQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ReviewLogQuery) Unique(unique bool) *ReviewLogQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ReviewLogQuery) Order(o ...reviewlog.OrderOption) *ReviewLogQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *ReviewLogQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reviewlog.Table, reviewlog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, reviewlog.UserTable, reviewlog.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCard chains the current query on the "card" edge.
func (_q *ReviewLogQuery) QueryCard() *CardQuery {
	query := (&CardClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reviewlog.Table, reviewlog.FieldID, selector),
			sqlgraph.To(card.Table, card.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, reviewlog.CardTable, reviewlog.CardColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ReviewLog entity from the query.
// Returns a *NotFoundError when no ReviewLog was found.
func (_q *ReviewLogQuery) First(ctx context.Context) (*ReviewLog, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{reviewlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ReviewLogQuery) FirstX(ctx context.Context) *ReviewLog {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReviewLog ID from the query.
// Returns a *NotFoundError when no ReviewLog ID was found.
func (_q *ReviewLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{reviewlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ReviewLogQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReviewLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReviewLog entity is found.
// Returns a *NotFoundError when no ReviewLog entities are found.
func (_q *ReviewLogQuery) Only(ctx context.Context) (*ReviewLog, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{reviewlog.Label}
	default:
		return nil, &NotSingularError{reviewlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ReviewLogQuery) OnlyX(ctx context.Context) *ReviewLog {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReviewLog ID in the query.
// Returns a *NotSingularError when more than one ReviewLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ReviewLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{reviewlog.Label}
	default:
		err = &NotSingularError{reviewlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ReviewLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReviewLogs.
func (_q *ReviewLogQuery) All(ctx context.Context) ([]*ReviewLog, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReviewLog, *ReviewLogQuery]()
	return withInterceptors[[]*ReviewLog](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ReviewLogQuery) AllX(ctx context.Context) []*ReviewLog {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReviewLog IDs.
func (_q *ReviewLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(reviewlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ReviewLogQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ReviewLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ReviewLogQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ReviewLogQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ReviewLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ReviewLogQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReviewLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ReviewLogQuery) Clone() *ReviewLogQuery {
	if _q == nil {
		return nil
	}
	return &ReviewLogQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]reviewlog.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ReviewLog{}, _q.predicates...),
		withUser:   _q.withUser.Clone(),
		withCard:   _q.withCard.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReviewLogQuery) WithUser(opts ...func(*UserQuery)) *ReviewLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithCard tells the query-builder to eager-load the nodes that are connected to
// the "card" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReviewLogQuery) WithCard(opts ...func(*CardQuery)) *ReviewLogQuery {
	query := (&CardClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCard = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReviewLog.Query().
//		GroupBy(reviewlog.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ReviewLogQuery) GroupBy(field string, fields ...string) *ReviewLogGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReviewLogGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = reviewlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.ReviewLog.Query().
//		Select(reviewlog.FieldUserID).
//		Scan(ctx, &v)
func (_q *ReviewLogQuery) Select(fields ...string) *ReviewLogSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ReviewLogSelect{ReviewLogQuery: _q}
	sbuild.label = reviewlog.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReviewLogSelect configured with the given aggregations.
func (_q *ReviewLogQuery) Aggregate(fns ...AggregateFunc) *ReviewLogSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ReviewLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !reviewlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ReviewLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReviewLog, error) {
	var (
		nodes       = []*ReviewLog{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withUser != nil,
			_q.withCard != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReviewLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReviewLog{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *ReviewLog, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCard; query != nil {
		if err := _q.loadCard(ctx, query, nodes, nil,
			func(n *ReviewLog, e *Card) { n.Edges.Card = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ReviewLogQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ReviewLog, init func(*ReviewLog), assign func(*ReviewLog, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ReviewLog)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ReviewLogQuery) loadCard(ctx context.Context, query *CardQuery, nodes []*ReviewLog, init func(*ReviewLog), assign func(*ReviewLog, *Card)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ReviewLog)
	for i := range nodes {
		fk := nodes[i].CardID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(card.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "card_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ReviewLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ReviewLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(reviewlog.Table, reviewlog.Columns, sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reviewlog.FieldID)
		for i := range fields {
			if fields[i] != reviewlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(reviewlog.FieldUserID)
		}
		if _q.withCard != nil {
			_spec.Node.AddColumnOnce(reviewlog.FieldCardID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ReviewLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(reviewlog.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = reviewlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReviewLogGroupBy is the group-by builder for ReviewLog entities.
type ReviewLogGroupBy struct {
	selector
	build *ReviewLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ReviewLogGroupBy) Aggregate(fns ...AggregateFunc) *ReviewLogGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ReviewLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReviewLogQuery, *ReviewLogGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ReviewLogGroupBy) sqlScan(ctx context.Context, root *ReviewLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReviewLogSelect is the builder for selecting fields of ReviewLog entities.
type ReviewLogSelect struct {
	*ReviewLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ReviewLogSelect) Aggregate(fns ...AggregateFunc) *ReviewLogSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ReviewLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReviewLogQuery, *ReviewLogSelect](ctx, _s.ReviewLogQuery, _s, _s.inters, v)
}

func (_s *ReviewLogSelect) sqlScan(ctx context.Context, root *ReviewLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
