// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jty/snapcard/ent/card"
	"github.com/jty/snapcard/ent/reviewlog"
	"github.com/jty/snapcard/ent/user"
)

// ReviewLogCreate is the builder for creating a ReviewLog entity.
type ReviewLogCreate struct {
	config
	mutation *ReviewLogMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ReviewLogCreate) SetUserID(v int) *ReviewLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCardID sets the "card_id" field.
func (_c *ReviewLogCreate) SetCardID(v int) *ReviewLogCreate {
	_c.mutation.SetCardID(v)
	return _c
}

// SetRating sets the "rating" field.
func (_c *ReviewLogCreate) SetRating(v int) *ReviewLogCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetReviewMode sets the "review_mode" field.
func (_c *ReviewLogCreate) SetReviewMode(v reviewlog.ReviewMode) *ReviewLogCreate {
	_c.mutation.SetReviewMode(v)
	return _c
}

// SetUserAnswer sets the "user_answer" field.
func (_c *ReviewLogCreate) SetUserAnswer(v string) *ReviewLogCreate {
	_c.mutation.SetUserAnswer(v)
	return _c
}

// SetNillableUserAnswer sets the "user_answer" field if the given value is not nil.
func (_c *ReviewLogCreate) SetNillableUserAnswer(v *string) *ReviewLogCreate {
	if v != nil {
		_c.SetUserAnswer(*v)
	}
	return _c
}

// SetAiCorrect sets the "ai_correct" field.
func (_c *ReviewLogCreate) SetAiCorrect(v bool) *ReviewLogCreate {
	_c.mutation.SetAiCorrect(v)
	return _c
}

// SetNillableAiCorrect sets the "ai_correct" field if the given value is not nil.
func (_c *ReviewLogCreate) SetNillableAiCorrect(v *bool) *ReviewLogCreate {
	if v != nil {
		_c.SetAiCorrect(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *ReviewLogCreate) SetReviewedAt(v time.Time) *ReviewLogCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *ReviewLogCreate) SetNillableReviewedAt(v *time.Time) *ReviewLogCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ReviewLogCreate) SetUser(v *User) *ReviewLogCreate {
	return _c.SetUserID(v.ID)
}

// SetCard sets the "card" edge to the Card entity.
func (_c *ReviewLogCreate) SetCard(v *Card) *ReviewLogCreate {
	return _c.SetCardID(v.ID)
}

// Mutation returns the ReviewLogMutation object of the builder.
func (_c *ReviewLogCreate) Mutation() *ReviewLogMutation {
	return _c.mutation
}

// Save creates the ReviewLog in the database.
func (_c *ReviewLogCreate) Save(ctx context.Context) (*ReviewLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReviewLogCreate) SaveX(ctx context.Context) *ReviewLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReviewLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReviewLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReviewLogCreate) defaults() {
	if _, ok := _c.mutation.ReviewedAt(); !ok {
		v := reviewlog.DefaultReviewedAt()
		_c.mutation.SetReviewedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReviewLogCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ReviewLog.user_id"`)}
	}
	if _, ok := _c.mutation.CardID(); !ok {
		return &ValidationError{Name: "card_id", err: errors.New(`ent: missing required field "ReviewLog.card_id"`)}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "ReviewLog.rating"`)}
	}
	if v, ok := _c.mutation.Rating(); ok {
		if err := reviewlog.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "ReviewLog.rating": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReviewMode(); !ok {
		return &ValidationError{Name: "review_mode", err: errors.New(`ent: missing required field "ReviewLog.review_mode"`)}
	}
	if v, ok := _c.mutation.ReviewMode(); ok {
		if err := reviewlog.ReviewModeValidator(v); err != nil {
			return &ValidationError{Name: "review_mode", err: fmt.Errorf(`ent: validator failed for field "ReviewLog.review_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReviewedAt(); !ok {
		return &ValidationError{Name: "reviewed_at", err: errors.New(`ent: missing required field "ReviewLog.reviewed_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ReviewLog.user"`)}
	}
	if len(_c.mutation.CardIDs()) == 0 {
		return &ValidationError{Name: "card", err: errors.New(`ent: missing required edge "ReviewLog.card"`)}
	}
	return nil
}

func (_c *ReviewLogCreate) sqlSave(ctx context.Context) (*ReviewLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReviewLogCreate) createSpec() (*ReviewLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ReviewLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reviewlog.Table, sqlgraph.NewFieldSpec(reviewlog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(reviewlog.FieldRating, field.TypeInt, value)
		_node.Rating = value
	}
	if value, ok := _c.mutation.ReviewMode(); ok {
		_spec.SetField(reviewlog.FieldReviewMode, field.TypeEnum, value)
		_node.ReviewMode = value
	}
	if value, ok := _c.mutation.UserAnswer(); ok {
		_spec.SetField(reviewlog.FieldUserAnswer, field.TypeString, value)
		_node.UserAnswer = &value
	}
	if value, ok := _c.mutation.AiCorrect(); ok {
		_spec.SetField(reviewlog.FieldAiCorrect, field.TypeBool, value)
		_node.AiCorrect = &value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(reviewlog.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.UserTable,
			Columns: []string{reviewlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reviewlog.CardTable,
			Columns: []string{reviewlog.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CardID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReviewLogCreateBulk is the builder for creating many ReviewLog entities in bulk.
type ReviewLogCreateBulk struct {
	config
	err      error
	builders []*ReviewLogCreate
}

// Save creates the ReviewLog entities in the database.
func (_c *ReviewLogCreateBulk) Save(ctx context.Context) ([]*ReviewLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReviewLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReviewLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReviewLogCreateBulk) SaveX(ctx context.Context) []*ReviewLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReviewLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReviewLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
