// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/jty/snapcard/ent/card"
	"github.com/jty/snapcard/ent/reviewlog"
	"github.com/jty/snapcard/ent/user"
)

// ReviewLog is the model entity for the ReviewLog schema.
type ReviewLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// CardID holds the value of the "card_id" field.
	CardID int `json:"card_id,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating int `json:"rating,omitempty"`
	// ReviewMode holds the value of the "review_mode" field.
	ReviewMode reviewlog.ReviewMode `json:"review_mode,omitempty"`
	// UserAnswer holds the value of the "user_answer" field.
	UserAnswer *string `json:"user_answer,omitempty"`
	// AiCorrect holds the value of the "ai_correct" field.
	AiCorrect *bool `json:"ai_correct,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt time.Time `json:"reviewed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReviewLogQuery when eager-loading is set.
	Edges        ReviewLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReviewLogEdges holds the relations/edges for other nodes in the graph.
type ReviewLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Card holds the value of the card edge.
	Card *Card `json:"card,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReviewLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CardOrErr returns the Card value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReviewLogEdges) CardOrErr() (*Card, error) {
	if e.Card != nil {
		return e.Card, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: card.Label}
	}
	return nil, &NotLoadedError{edge: "card"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReviewLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reviewlog.FieldAiCorrect:
			values[i] = new(sql.NullBool)
		case reviewlog.FieldID, reviewlog.FieldUserID, reviewlog.FieldCardID, reviewlog.FieldRating:
			values[i] = new(sql.NullInt64)
		case reviewlog.FieldReviewMode, reviewlog.FieldUserAnswer:
			values[i] = new(sql.NullString)
		case reviewlog.FieldReviewedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReviewLog fields.
func (_m *ReviewLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reviewlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case reviewlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case reviewlog.FieldCardID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field card_id", values[i])
			} else if value.Valid {
				_m.CardID = int(value.Int64)
			}
		case reviewlog.FieldRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = int(value.Int64)
			}
		case reviewlog.FieldReviewMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_mode", values[i])
			} else if value.Valid {
				_m.ReviewMode = reviewlog.ReviewMode(value.String)
			}
		case reviewlog.FieldUserAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_answer", values[i])
			} else if value.Valid {
				_m.UserAnswer = new(string)
				*_m.UserAnswer = value.String
			}
		case reviewlog.FieldAiCorrect:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ai_correct", values[i])
			} else if value.Valid {
				_m.AiCorrect = new(bool)
				*_m.AiCorrect = value.Bool
			}
		case reviewlog.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReviewLog.
// This includes values selected through modifiers, order, etc.
func (_m *ReviewLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ReviewLog entity.
func (_m *ReviewLog) QueryUser() *UserQuery {
	return NewReviewLogClient(_m.config).QueryUser(_m)
}

// QueryCard queries the "card" edge of the ReviewLog entity.
func (_m *ReviewLog) QueryCard() *CardQuery {
	return NewReviewLogClient(_m.config).QueryCard(_m)
}

// Update returns a builder for updating this ReviewLog.
// Note that you need to call ReviewLog.Unwrap() before calling this method if this ReviewLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReviewLog) Update() *ReviewLogUpdateOne {
	return NewReviewLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReviewLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReviewLog) Unwrap() *ReviewLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReviewLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReviewLog) String() string {
	var builder strings.Builder
	builder.WriteString("ReviewLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("card_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CardID))
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rating))
	builder.WriteString(", ")
	builder.WriteString("review_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewMode))
	builder.WriteString(", ")
	if v := _m.UserAnswer; v != nil {
		builder.WriteString("user_answer=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AiCorrect; v != nil {
		builder.WriteString("ai_correct=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reviewed_at=")
	builder.WriteString(_m.ReviewedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReviewLogs is a parsable slice of ReviewLog.
type ReviewLogs []*ReviewLog
