// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/jty/snapcard/ent/card"
	"github.com/jty/snapcard/ent/deck"
	"github.com/jty/snapcard/ent/reviewlog"
	"github.com/jty/snapcard/ent/schema"
	"github.com/jty/snapcard/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cardFields := schema.Card{}.Fields()
	_ = cardFields
	// cardDescFront is the schema descriptor for front field.
	cardDescFront := cardFields[2].Descriptor()
	// card.FrontValidator is a validator for the "front" field. It is called by the builders before save.
	card.FrontValidator = cardDescFront.Validators[0].(func(string) error)
	// cardDescBack is the schema descriptor for back field.
	cardDescBack := cardFields[3].Descriptor()
	// card.BackValidator is a validator for the "back" field. It is called by the builders before save.
	card.BackValidator = cardDescBack.Validators[0].(func(string) error)
	// cardDescStability is the schema descriptor for stability field.
	cardDescStability := cardFields[6].Descriptor()
	// card.DefaultStability holds the default value on creation for the stability field.
	card.DefaultStability = cardDescStability.Default.(float64)
	// cardDescDifficulty is the schema descriptor for difficulty field.
	cardDescDifficulty := cardFields[7].Descriptor()
	// card.DefaultDifficulty holds the default value on creation for the difficulty field.
	card.DefaultDifficulty = cardDescDifficulty.Default.(float64)
	// cardDescDueDate is the schema descriptor for due_date field.
	cardDescDueDate := cardFields[8].Descriptor()
	// card.DefaultDueDate holds the default value on creation for the due_date field.
	card.DefaultDueDate = cardDescDueDate.Default.(func() time.Time)
	// cardDescReps is the schema descriptor for reps field.
	cardDescReps := cardFields[9].Descriptor()
	// card.DefaultReps holds the default value on creation for the reps field.
	card.DefaultReps = cardDescReps.Default.(int)
	// cardDescLapses is the schema descriptor for lapses field.
	cardDescLapses := cardFields[10].Descriptor()
	// card.DefaultLapses holds the default value on creation for the lapses field.
	card.DefaultLapses = cardDescLapses.Default.(int)
	// cardDescCreatedAt is the schema descriptor for created_at field.
	cardDescCreatedAt := cardFields[12].Descriptor()
	// card.DefaultCreatedAt holds the default value on creation for the created_at field.
	card.DefaultCreatedAt = cardDescCreatedAt.Default.(func() time.Time)
	// cardDescUpdatedAt is the schema descriptor for updated_at field.
	cardDescUpdatedAt := cardFields[13].Descriptor()
	// card.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	card.DefaultUpdatedAt = cardDescUpdatedAt.Default.(func() time.Time)
	// card.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	card.UpdateDefaultUpdatedAt = cardDescUpdatedAt.UpdateDefault.(func() time.Time)
	deckFields := schema.Deck{}.Fields()
	_ = deckFields
	// deckDescName is the schema descriptor for name field.
	deckDescName := deckFields[1].Descriptor()
	// deck.NameValidator is a validator for the "name" field. It is called by the builders before save.
	deck.NameValidator = deckDescName.Validators[0].(func(string) error)
	// deckDescCreatedAt is the schema descriptor for created_at field.
	deckDescCreatedAt := deckFields[2].Descriptor()
	// deck.DefaultCreatedAt holds the default value on creation for the created_at field.
	deck.DefaultCreatedAt = deckDescCreatedAt.Default.(func() time.Time)
	// deckDescUpdatedAt is the schema descriptor for updated_at field.
	deckDescUpdatedAt := deckFields[3].Descriptor()
	// deck.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deck.DefaultUpdatedAt = deckDescUpdatedAt.Default.(func() time.Time)
	// deck.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deck.UpdateDefaultUpdatedAt = deckDescUpdatedAt.UpdateDefault.(func() time.Time)
	reviewlogFields := schema.ReviewLog{}.Fields()
	_ = reviewlogFields
	// reviewlogDescRating is the schema descriptor for rating field.
	reviewlogDescRating := reviewlogFields[2].Descriptor()
	// reviewlog.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	reviewlog.RatingValidator = func() func(int) error {
		validators := reviewlogDescRating.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(rating int) error {
			for _, fn := range fns {
				if err := fn(rating); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// reviewlogDescReviewedAt is the schema descriptor for reviewed_at field.
	reviewlogDescReviewedAt := reviewlogFields[6].Descriptor()
	// reviewlog.DefaultReviewedAt holds the default value on creation for the reviewed_at field.
	reviewlog.DefaultReviewedAt = reviewlogDescReviewedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescOpenid is the schema descriptor for openid field.
	userDescOpenid := userFields[0].Descriptor()
	// user.OpenidValidator is a validator for the "openid" field. It is called by the builders before save.
	user.OpenidValidator = userDescOpenid.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
