// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Deck is the predicate function for deck builders.
type Deck func(*sql.Selector)

// ReviewLog is the predicate function for reviewlog builders.
type ReviewLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
