// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CardsColumns holds the columns for the "cards" table.
	CardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "front", Type: field.TypeString},
		{Name: "back", Type: field.TypeString},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "source_image_url", Type: field.TypeString, Nullable: true},
		{Name: "stability", Type: field.TypeFloat64, Default: 0},
		{Name: "difficulty", Type: field.TypeFloat64, Default: 0},
		{Name: "due_date", Type: field.TypeTime},
		{Name: "reps", Type: field.TypeInt, Default: 0},
		{Name: "lapses", Type: field.TypeInt, Default: 0},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"new", "learning", "review", "relearning"}, Default: "new"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deck_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// CardsTable holds the schema information for the "cards" table.
	CardsTable = &schema.Table{
		Name:       "cards",
		Columns:    CardsColumns,
		PrimaryKey: []*schema.Column{CardsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cards_decks_cards",
				Columns:    []*schema.Column{CardsColumns[13]},
				RefColumns: []*schema.Column{DecksColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "cards_users_cards",
				Columns:    []*schema.Column{CardsColumns[14]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DecksColumns holds the columns for the "decks" table.
	DecksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// DecksTable holds the schema information for the "decks" table.
	DecksTable = &schema.Table{
		Name:       "decks",
		Columns:    DecksColumns,
		PrimaryKey: []*schema.Column{DecksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "decks_users_decks",
				Columns:    []*schema.Column{DecksColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ReviewLogsColumns holds the columns for the "review_logs" table.
	ReviewLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "rating", Type: field.TypeInt},
		{Name: "review_mode", Type: field.TypeEnum, Enums: []string{"self_rate", "ai_judge"}},
		{Name: "user_answer", Type: field.TypeString, Nullable: true},
		{Name: "ai_correct", Type: field.TypeBool, Nullable: true},
		{Name: "reviewed_at", Type: field.TypeTime},
		{Name: "card_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// ReviewLogsTable holds the schema information for the "review_logs" table.
	ReviewLogsTable = &schema.Table{
		Name:       "review_logs",
		Columns:    ReviewLogsColumns,
		PrimaryKey: []*schema.Column{ReviewLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "review_logs_cards_review_logs",
				Columns:    []*schema.Column{ReviewLogsColumns[6]},
				RefColumns: []*schema.Column{CardsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "review_logs_users_review_logs",
				Columns:    []*schema.Column{ReviewLogsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "openid", Type: field.TypeString, Unique: true},
		{Name: "nickname", Type: field.TypeString, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CardsTable,
		DecksTable,
		ReviewLogsTable,
		UsersTable,
	}
)

func init() {
	CardsTable.ForeignKeys[0].RefTable = DecksTable
	CardsTable.ForeignKeys[1].RefTable = UsersTable
	DecksTable.ForeignKeys[0].RefTable = UsersTable
	ReviewLogsTable.ForeignKeys[0].RefTable = CardsTable
	ReviewLogsTable.ForeignKeys[1].RefTable = UsersTable
}
