// Code generated by ent, DO NOT EDIT.

package reviewlog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the reviewlog type in the database.
	Label = "review_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCardID holds the string denoting the card_id field in the database.
	FieldCardID = "card_id"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldReviewMode holds the string denoting the review_mode field in the database.
	FieldReviewMode = "review_mode"
	// FieldUserAnswer holds the string denoting the user_answer field in the database.
	FieldUserAnswer = "user_answer"
	// FieldAiCorrect holds the string denoting the ai_correct field in the database.
	FieldAiCorrect = "ai_correct"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewed_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeCard holds the string denoting the card edge name in mutations.
	EdgeCard = "card"
	// Table holds the table name of the reviewlog in the database.
	Table = "review_logs"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "review_logs"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// CardTable is the table that holds the card relation/edge.
	CardTable = "review_logs"
	// CardInverseTable is the table name for the Card entity.
	// It exists in this package in order to avoid circular dependency with the "card" package.
	CardInverseTable = "cards"
	// CardColumn is the table column denoting the card relation/edge.
	CardColumn = "card_id"
)

// Columns holds all SQL columns for reviewlog fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldCardID,
	FieldRating,
	FieldReviewMode,
	FieldUserAnswer,
	FieldAiCorrect,
	FieldReviewedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	RatingValidator func(int) error
	// DefaultReviewedAt holds the default value on creation for the "reviewed_at" field.
	DefaultReviewedAt func() time.Time
)

// ReviewMode defines the type for the "review_mode" enum field.
type ReviewMode string

// ReviewMode values.
const (
	ReviewModeSelfRate ReviewMode = "self_rate"
	ReviewModeAiJudge  ReviewMode = "ai_judge"
)

func (rm ReviewMode) String() string {
	return string(rm)
}

// ReviewModeValidator is a validator for the "review_mode" field enum values. It is called by the builders before save.
func ReviewModeValidator(rm ReviewMode) error {
	switch rm {
	case ReviewModeSelfRate, ReviewModeAiJudge:
		return nil
	default:
		return fmt.Errorf("reviewlog: invalid enum value for review_mode field: %q", rm)
	}
}

// OrderOption defines the ordering options for the ReviewLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCardID orders the results by the card_id field.
func ByCardID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCardID, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByReviewMode orders the results by the review_mode field.
func ByReviewMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewMode, opts...).ToFunc()
}

// ByUserAnswer orders the results by the user_answer field.
func ByUserAnswer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAnswer, opts...).ToFunc()
}

// ByAiCorrect orders the results by the ai_correct field.
func ByAiCorrect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiCorrect, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCardField orders the results by card field.
func ByCardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCardStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newCardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CardInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CardTable, CardColumn),
	)
}
