// Code generated by ent, DO NOT EDIT.

package reviewlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jty/snapcard/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldUserID, v))
}

// CardID applies equality check predicate on the "card_id" field. It's identical to CardIDEQ.
func CardID(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldCardID, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldRating, v))
}

// UserAnswer applies equality check predicate on the "user_answer" field. It's identical to UserAnswerEQ.
func UserAnswer(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldUserAnswer, v))
}

// AiCorrect applies equality check predicate on the "ai_correct" field. It's identical to AiCorrectEQ.
func AiCorrect(v bool) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldAiCorrect, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldReviewedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldUserID, vs...))
}

// CardIDEQ applies the EQ predicate on the "card_id" field.
func CardIDEQ(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldCardID, v))
}

// CardIDNEQ applies the NEQ predicate on the "card_id" field.
func CardIDNEQ(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldCardID, v))
}

// CardIDIn applies the In predicate on the "card_id" field.
func CardIDIn(vs ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldCardID, vs...))
}

// CardIDNotIn applies the NotIn predicate on the "card_id" field.
func CardIDNotIn(vs ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldCardID, vs...))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v int) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLTE(FieldRating, v))
}

// ReviewModeEQ applies the EQ predicate on the "review_mode" field.
func ReviewModeEQ(v ReviewMode) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldReviewMode, v))
}

// ReviewModeNEQ applies the NEQ predicate on the "review_mode" field.
func ReviewModeNEQ(v ReviewMode) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldReviewMode, v))
}

// ReviewModeIn applies the In predicate on the "review_mode" field.
func ReviewModeIn(vs ...ReviewMode) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldReviewMode, vs...))
}

// ReviewModeNotIn applies the NotIn predicate on the "review_mode" field.
func ReviewModeNotIn(vs ...ReviewMode) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldReviewMode, vs...))
}

// UserAnswerEQ applies the EQ predicate on the "user_answer" field.
func UserAnswerEQ(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldUserAnswer, v))
}

// UserAnswerNEQ applies the NEQ predicate on the "user_answer" field.
func UserAnswerNEQ(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldUserAnswer, v))
}

// UserAnswerIn applies the In predicate on the "user_answer" field.
func UserAnswerIn(vs ...string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldUserAnswer, vs...))
}

// UserAnswerNotIn applies the NotIn predicate on the "user_answer" field.
func UserAnswerNotIn(vs ...string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldUserAnswer, vs...))
}

// UserAnswerGT applies the GT predicate on the "user_answer" field.
func UserAnswerGT(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGT(FieldUserAnswer, v))
}

// UserAnswerGTE applies the GTE predicate on the "user_answer" field.
func UserAnswerGTE(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGTE(FieldUserAnswer, v))
}

// UserAnswerLT applies the LT predicate on the "user_answer" field.
func UserAnswerLT(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLT(FieldUserAnswer, v))
}

// UserAnswerLTE applies the LTE predicate on the "user_answer" field.
func UserAnswerLTE(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLTE(FieldUserAnswer, v))
}

// UserAnswerContains applies the Contains predicate on the "user_answer" field.
func UserAnswerContains(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldContains(FieldUserAnswer, v))
}

// UserAnswerHasPrefix applies the HasPrefix predicate on the "user_answer" field.
func UserAnswerHasPrefix(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldHasPrefix(FieldUserAnswer, v))
}

// UserAnswerHasSuffix applies the HasSuffix predicate on the "user_answer" field.
func UserAnswerHasSuffix(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldHasSuffix(FieldUserAnswer, v))
}

// UserAnswerIsNil applies the IsNil predicate on the "user_answer" field.
func UserAnswerIsNil() predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIsNull(FieldUserAnswer))
}

// UserAnswerNotNil applies the NotNil predicate on the "user_answer" field.
func UserAnswerNotNil() predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotNull(FieldUserAnswer))
}

// UserAnswerEqualFold applies the EqualFold predicate on the "user_answer" field.
func UserAnswerEqualFold(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEqualFold(FieldUserAnswer, v))
}

// UserAnswerContainsFold applies the ContainsFold predicate on the "user_answer" field.
func UserAnswerContainsFold(v string) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldContainsFold(FieldUserAnswer, v))
}

// AiCorrectEQ applies the EQ predicate on the "ai_correct" field.
func AiCorrectEQ(v bool) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldAiCorrect, v))
}

// AiCorrectNEQ applies the NEQ predicate on the "ai_correct" field.
func AiCorrectNEQ(v bool) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldAiCorrect, v))
}

// AiCorrectIsNil applies the IsNil predicate on the "ai_correct" field.
func AiCorrectIsNil() predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIsNull(FieldAiCorrect))
}

// AiCorrectNotNil applies the NotNil predicate on the "ai_correct" field.
func AiCorrectNotNil() predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotNull(FieldAiCorrect))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.ReviewLog {
	return predicate.ReviewLog(sql.FieldLTE(FieldReviewedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ReviewLog {
	return predicate.ReviewLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ReviewLog {
	return predicate.ReviewLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCard applies the HasEdge predicate on the "card" edge.
func HasCard() predicate.ReviewLog {
	return predicate.ReviewLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CardTable, CardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCardWith applies the HasEdge predicate on the "card" edge with a given conditions (other predicates).
func HasCardWith(preds ...predicate.Card) predicate.ReviewLog {
	return predicate.ReviewLog(func(s *sql.Selector) {
		step := newCardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReviewLog) predicate.ReviewLog {
	return predicate.ReviewLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReviewLog) predicate.ReviewLog {
	return predicate.ReviewLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReviewLog) predicate.ReviewLog {
	return predicate.ReviewLog(sql.NotPredicates(p))
}
