// Code generated by ent, DO NOT EDIT.

package card

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the card type in the database.
	Label = "card"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDeckID holds the string denoting the deck_id field in the database.
	FieldDeckID = "deck_id"
	// FieldFront holds the string denoting the front field in the database.
	FieldFront = "front"
	// FieldBack holds the string denoting the back field in the database.
	FieldBack = "back"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldSourceImageURL holds the string denoting the source_image_url field in the database.
	FieldSourceImageURL = "source_image_url"
	// FieldStability holds the string denoting the stability field in the database.
	FieldStability = "stability"
	// FieldDifficulty holds the string denoting the difficulty field in the database.
	FieldDifficulty = "difficulty"
	// FieldDueDate holds the string denoting the due_date field in the database.
	FieldDueDate = "due_date"
	// FieldReps holds the string denoting the reps field in the database.
	FieldReps = "reps"
	// FieldLapses holds the string denoting the lapses field in the database.
	FieldLapses = "lapses"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeDeck holds the string denoting the deck edge name in mutations.
	EdgeDeck = "deck"
	// EdgeReviewLogs holds the string denoting the review_logs edge name in mutations.
	EdgeReviewLogs = "review_logs"
	// Table holds the table name of the card in the database.
	Table = "cards"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "cards"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// DeckTable is the table that holds the deck relation/edge.
	DeckTable = "cards"
	// DeckInverseTable is the table name for the Deck entity.
	// It exists in this package in order to avoid circular dependency with the "deck" package.
	DeckInverseTable = "decks"
	// DeckColumn is the table column denoting the deck relation/edge.
	DeckColumn = "deck_id"
	// ReviewLogsTable is the table that holds the review_logs relation/edge.
	ReviewLogsTable = "review_logs"
	// ReviewLogsInverseTable is the table name for the ReviewLog entity.
	// It exists in this package in order to avoid circular dependency with the "reviewlog" package.
	ReviewLogsInverseTable = "review_logs"
	// ReviewLogsColumn is the table column denoting the review_logs relation/edge.
	ReviewLogsColumn = "card_id"
)

// Columns holds all SQL columns for card fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDeckID,
	FieldFront,
	FieldBack,
	FieldTags,
	FieldSourceImageURL,
	FieldStability,
	FieldDifficulty,
	FieldDueDate,
	FieldReps,
	FieldLapses,
	FieldState,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FrontValidator is a validator for the "front" field. It is called by the builders before save.
	FrontValidator func(string) error
	// BackValidator is a validator for the "back" field. It is called by the builders before save.
	BackValidator func(string) error
	// DefaultStability holds the default value on creation for the "stability" field.
	DefaultStability float64
	// DefaultDifficulty holds the default value on creation for the "difficulty" field.
	DefaultDifficulty float64
	// DefaultDueDate holds the default value on creation for the "due_date" field.
	DefaultDueDate func() time.Time
	// DefaultReps holds the default value on creation for the "reps" field.
	DefaultReps int
	// DefaultLapses holds the default value on creation for the "lapses" field.
	DefaultLapses int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// State defines the type for the "state" enum field.
type State string

// StateNew is the default value of the State enum.
const DefaultState = StateNew

// State values.
const (
	StateNew        State = "new"
	StateLearning   State = "learning"
	StateReview     State = "review"
	StateRelearning State = "relearning"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateNew, StateLearning, StateReview, StateRelearning:
		return nil
	default:
		return fmt.Errorf("card: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the Card queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDeckID orders the results by the deck_id field.
func ByDeckID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeckID, opts...).ToFunc()
}

// ByFront orders the results by the front field.
func ByFront(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFront, opts...).ToFunc()
}

// ByBack orders the results by the back field.
func ByBack(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBack, opts...).ToFunc()
}

// BySourceImageURL orders the results by the source_image_url field.
func BySourceImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceImageURL, opts...).ToFunc()
}

// ByStability orders the results by the stability field.
func ByStability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStability, opts...).ToFunc()
}

// ByDifficulty orders the results by the difficulty field.
func ByDifficulty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDifficulty, opts...).ToFunc()
}

// ByDueDate orders the results by the due_date field.
func ByDueDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueDate, opts...).ToFunc()
}

// ByReps orders the results by the reps field.
func ByReps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReps, opts...).ToFunc()
}

// ByLapses orders the results by the lapses field.
func ByLapses(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLapses, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByDeckField orders the results by deck field.
func ByDeckField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeckStep(), sql.OrderByField(field, opts...))
	}
}

// ByReviewLogsCount orders the results by review_logs count.
func ByReviewLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReviewLogsStep(), opts...)
	}
}

// ByReviewLogs orders the results by review_logs terms.
func ByReviewLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newDeckStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeckInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeckTable, DeckColumn),
	)
}
func newReviewLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReviewLogsTable, ReviewLogsColumn),
	)
}
