// Code generated by ent, DO NOT EDIT.

package card

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jty/snapcard/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUserID, v))
}

// DeckID applies equality check predicate on the "deck_id" field. It's identical to DeckIDEQ.
func DeckID(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDeckID, v))
}

// Front applies equality check predicate on the "front" field. It's identical to FrontEQ.
func Front(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldFront, v))
}

// Back applies equality check predicate on the "back" field. It's identical to BackEQ.
func Back(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldBack, v))
}

// SourceImageURL applies equality check predicate on the "source_image_url" field. It's identical to SourceImageURLEQ.
func SourceImageURL(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldSourceImageURL, v))
}

// Stability applies equality check predicate on the "stability" field. It's identical to StabilityEQ.
func Stability(v float64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldStability, v))
}

// Difficulty applies equality check predicate on the "difficulty" field. It's identical to DifficultyEQ.
func Difficulty(v float64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDifficulty, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDueDate, v))
}

// Reps applies equality check predicate on the "reps" field. It's identical to RepsEQ.
func Reps(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldReps, v))
}

// Lapses applies equality check predicate on the "lapses" field. It's identical to LapsesEQ.
func Lapses(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldLapses, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldUserID, vs...))
}

// DeckIDEQ applies the EQ predicate on the "deck_id" field.
func DeckIDEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDeckID, v))
}

// DeckIDNEQ applies the NEQ predicate on the "deck_id" field.
func DeckIDNEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldDeckID, v))
}

// DeckIDIn applies the In predicate on the "deck_id" field.
func DeckIDIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldDeckID, vs...))
}

// DeckIDNotIn applies the NotIn predicate on the "deck_id" field.
func DeckIDNotIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldDeckID, vs...))
}

// FrontEQ applies the EQ predicate on the "front" field.
func FrontEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldFront, v))
}

// FrontNEQ applies the NEQ predicate on the "front" field.
func FrontNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldFront, v))
}

// FrontIn applies the In predicate on the "front" field.
func FrontIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldFront, vs...))
}

// FrontNotIn applies the NotIn predicate on the "front" field.
func FrontNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldFront, vs...))
}

// FrontGT applies the GT predicate on the "front" field.
func FrontGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldFront, v))
}

// FrontGTE applies the GTE predicate on the "front" field.
func FrontGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldFront, v))
}

// FrontLT applies the LT predicate on the "front" field.
func FrontLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldFront, v))
}

// FrontLTE applies the LTE predicate on the "front" field.
func FrontLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldFront, v))
}

// FrontContains applies the Contains predicate on the "front" field.
func FrontContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldFront, v))
}

// FrontHasPrefix applies the HasPrefix predicate on the "front" field.
func FrontHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldFront, v))
}

// FrontHasSuffix applies the HasSuffix predicate on the "front" field.
func FrontHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldFront, v))
}

// FrontEqualFold applies the EqualFold predicate on the "front" field.
func FrontEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldFront, v))
}

// FrontContainsFold applies the ContainsFold predicate on the "front" field.
func FrontContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldFront, v))
}

// BackEQ applies the EQ predicate on the "back" field.
func BackEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldBack, v))
}

// BackNEQ applies the NEQ predicate on the "back" field.
func BackNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldBack, v))
}

// BackIn applies the In predicate on the "back" field.
func BackIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldBack, vs...))
}

// BackNotIn applies the NotIn predicate on the "back" field.
func BackNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldBack, vs...))
}

// BackGT applies the GT predicate on the "back" field.
func BackGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldBack, v))
}

// BackGTE applies the GTE predicate on the "back" field.
func BackGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldBack, v))
}

// BackLT applies the LT predicate on the "back" field.
func BackLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldBack, v))
}

// BackLTE applies the LTE predicate on the "back" field.
func BackLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldBack, v))
}

// BackContains applies the Contains predicate on the "back" field.
func BackContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldBack, v))
}

// BackHasPrefix applies the HasPrefix predicate on the "back" field.
func BackHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldBack, v))
}

// BackHasSuffix applies the HasSuffix predicate on the "back" field.
func BackHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldBack, v))
}

// BackEqualFold applies the EqualFold predicate on the "back" field.
func BackEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldBack, v))
}

// BackContainsFold applies the ContainsFold predicate on the "back" field.
func BackContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldBack, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldTags))
}

// SourceImageURLEQ applies the EQ predicate on the "source_image_url" field.
func SourceImageURLEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldSourceImageURL, v))
}

// SourceImageURLNEQ applies the NEQ predicate on the "source_image_url" field.
func SourceImageURLNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldSourceImageURL, v))
}

// SourceImageURLIn applies the In predicate on the "source_image_url" field.
func SourceImageURLIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldSourceImageURL, vs...))
}

// SourceImageURLNotIn applies the NotIn predicate on the "source_image_url" field.
func SourceImageURLNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldSourceImageURL, vs...))
}

// SourceImageURLGT applies the GT predicate on the "source_image_url" field.
func SourceImageURLGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldSourceImageURL, v))
}

// SourceImageURLGTE applies the GTE predicate on the "source_image_url" field.
func SourceImageURLGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldSourceImageURL, v))
}

// SourceImageURLLT applies the LT predicate on the "source_image_url" field.
func SourceImageURLLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldSourceImageURL, v))
}

// SourceImageURLLTE applies the LTE predicate on the "source_image_url" field.
func SourceImageURLLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldSourceImageURL, v))
}

// SourceImageURLContains applies the Contains predicate on the "source_image_url" field.
func SourceImageURLContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldSourceImageURL, v))
}

// SourceImageURLHasPrefix applies the HasPrefix predicate on the "source_image_url" field.
func SourceImageURLHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldSourceImageURL, v))
}

// SourceImageURLHasSuffix applies the HasSuffix predicate on the "source_image_url" field.
func SourceImageURLHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldSourceImageURL, v))
}

// SourceImageURLIsNil applies the IsNil predicate on the "source_image_url" field.
func SourceImageURLIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldSourceImageURL))
}

// SourceImageURLNotNil applies the NotNil predicate on the "source_image_url" field.
func SourceImageURLNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldSourceImageURL))
}

// SourceImageURLEqualFold applies the EqualFold predicate on the "source_image_url" field.
func SourceImageURLEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldSourceImageURL, v))
}

// SourceImageURLContainsFold applies the ContainsFold predicate on the "source_image_url" field.
func SourceImageURLContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldSourceImageURL, v))
}

// StabilityEQ applies the EQ predicate on the "stability" field.
func StabilityEQ(v float64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldStability, v))
}

// StabilityNEQ applies the NEQ predicate on the "stability" field.
func StabilityNEQ(v float64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldStability, v))
}

// StabilityIn applies the In predicate on the "stability" field.
func StabilityIn(vs ...float64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldStability, vs...))
}

// StabilityNotIn applies the NotIn predicate on the "stability" field.
func StabilityNotIn(vs ...float64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldStability, vs...))
}

// StabilityGT applies the GT predicate on the "stability" field.
func StabilityGT(v float64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldStability, v))
}

// StabilityGTE applies the GTE predicate on the "stability" field.
func StabilityGTE(v float64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldStability, v))
}

// StabilityLT applies the LT predicate on the "stability" field.
func StabilityLT(v float64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldStability, v))
}

// StabilityLTE applies the LTE predicate on the "stability" field.
func StabilityLTE(v float64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldStability, v))
}

// DifficultyEQ applies the EQ predicate on the "difficulty" field.
func DifficultyEQ(v float64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDifficulty, v))
}

// DifficultyNEQ applies the NEQ predicate on the "difficulty" field.
func DifficultyNEQ(v float64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldDifficulty, v))
}

// DifficultyIn applies the In predicate on the "difficulty" field.
func DifficultyIn(vs ...float64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldDifficulty, vs...))
}

// DifficultyNotIn applies the NotIn predicate on the "difficulty" field.
func DifficultyNotIn(vs ...float64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldDifficulty, vs...))
}

// DifficultyGT applies the GT predicate on the "difficulty" field.
func DifficultyGT(v float64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldDifficulty, v))
}

// DifficultyGTE applies the GTE predicate on the "difficulty" field.
func DifficultyGTE(v float64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldDifficulty, v))
}

// DifficultyLT applies the LT predicate on the "difficulty" field.
func DifficultyLT(v float64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldDifficulty, v))
}

// DifficultyLTE applies the LTE predicate on the "difficulty" field.
func DifficultyLTE(v float64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldDifficulty, v))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldDueDate, v))
}

// RepsEQ applies the EQ predicate on the "reps" field.
func RepsEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldReps, v))
}

// RepsNEQ applies the NEQ predicate on the "reps" field.
func RepsNEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldReps, v))
}

// RepsIn applies the In predicate on the "reps" field.
func RepsIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldReps, vs...))
}

// RepsNotIn applies the NotIn predicate on the "reps" field.
func RepsNotIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldReps, vs...))
}

// RepsGT applies the GT predicate on the "reps" field.
func RepsGT(v int) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldReps, v))
}

// RepsGTE applies the GTE predicate on the "reps" field.
func RepsGTE(v int) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldReps, v))
}

// RepsLT applies the LT predicate on the "reps" field.
func RepsLT(v int) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldReps, v))
}

// RepsLTE applies the LTE predicate on the "reps" field.
func RepsLTE(v int) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldReps, v))
}

// LapsesEQ applies the EQ predicate on the "lapses" field.
func LapsesEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldLapses, v))
}

// LapsesNEQ applies the NEQ predicate on the "lapses" field.
func LapsesNEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldLapses, v))
}

// LapsesIn applies the In predicate on the "lapses" field.
func LapsesIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldLapses, vs...))
}

// LapsesNotIn applies the NotIn predicate on the "lapses" field.
func LapsesNotIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldLapses, vs...))
}

// LapsesGT applies the GT predicate on the "lapses" field.
func LapsesGT(v int) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldLapses, v))
}

// LapsesGTE applies the GTE predicate on the "lapses" field.
func LapsesGTE(v int) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldLapses, v))
}

// LapsesLT applies the LT predicate on the "lapses" field.
func LapsesLT(v int) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldLapses, v))
}

// LapsesLTE applies the LTE predicate on the "lapses" field.
func LapsesLTE(v int) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldLapses, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldState, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeck applies the HasEdge predicate on the "deck" edge.
func HasDeck() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeckTable, DeckColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeckWith applies the HasEdge predicate on the "deck" edge with a given conditions (other predicates).
func HasDeckWith(preds ...predicate.Deck) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newDeckStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReviewLogs applies the HasEdge predicate on the "review_logs" edge.
func HasReviewLogs() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReviewLogsTable, ReviewLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewLogsWith applies the HasEdge predicate on the "review_logs" edge with a given conditions (other predicates).
func HasReviewLogsWith(preds ...predicate.ReviewLog) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newReviewLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Card) predicate.Card {
	return predicate.Card(sql.NotPredicates(p))
}
